DEPT_WEBSITES_FACULTY = {
    "berkeley": ["https://statistics.berkeley.edu/people/faculty"],
    "chicago": ["https://stat.uchicago.edu/people/#faculty"],
    "cmu": [
        "https://www.cmu.edu/dietrich/statistics-datascience/people/faculty/index.html"
    ],
    "columbia": [
        "https://stat.columbia.edu/department-directory/faculty-and-lecturers/"
    ],
    "cornell": ["https://stat.cornell.edu/people/faculty"],
    "duke": ["https://stat.duke.edu/people/appointed-faculty/primary-faculty"],
    "florida": ["https://stat.ufl.edu/people/faculty/"],
    "harvard": ["https://statistics.fas.harvard.edu/faculty"],
    "iowa": ["https://www.stat.iastate.edu/faculty"],
    "minnesota": ["https://cla.umn.edu/statistics/people/faculty"],
    # "michigan": ["https://lsa.umich.edu/stats/people/faculty.html"],
    "nc_state": ["https://statistics.sciences.ncsu.edu/group/faculty/"],
    "ohio": ["https://stat.osu.edu/people?field_appointment_target_id[16]=16"],
    "penn": ["https://statistics.wharton.upenn.edu/faculty/faculty-list/"],
    "penn_state": [
        "https://science.psu.edu/people?person_type=47&department=17&unit=All&items_per_page=200"
    ],
    "purdue": ["https://www.stat.purdue.edu/people/faculty/index.html"],
    #"rice": ["https://statistics.rice.edu/people/faculty"],
    "rutgers": [
        "https://statistics.rutgers.edu/people-pages/faculty",
        "https://statistics.rutgers.edu/people-pages/adjunct-faculty",
    ],
    "stanford": ["https://statistics.stanford.edu/people/faculty"],
    "ucdavis": [
        "https://statistics.ucdavis.edu/person-type/faculty",
        "https://statistics.ucdavis.edu/person-type/faculty?page=1",
        "https://statistics.ucdavis.edu/person-type/faculty?page=2",
    ],
    "uci": ["https://www.stat.uci.edu/faculty/"],
    "ucla": ["http://directory.stat.ucla.edu/faculty/all-faculty/"],
    "texas_am": ["https://stat.tamu.edu/people/#faculty-all"],
    "uiuc": ["https://stat.illinois.edu/directory/faculty"],
    "unc": [
        "https://stor.unc.edu/people/faculty/",
        "https://stor.unc.edu/people/adjuncts-joint/",
    ],
    #"utaustin": ["https://stat.utexas.edu/people?type=Tenure/Tenure%20Track%20Faculty"],
    "washington": ["https://stat.uw.edu/about-us/people/faculty"],
    "wisconsin": ["https://stat.wisc.edu/people-main-faculty/"],
    "yale": ["https://statistics.yale.edu/people/faculty"],
}

DEPT_WEBSITES_PHD = {
    "berkeley": ["https://statistics.berkeley.edu/people/students/phd"],
    "chicago": ["https://stat.uchicago.edu/people/#phd-students"],
    "cmu": [
        "https://www.cmu.edu/dietrich/statistics-datascience/people/phd/index.html"
    ],
    "columbia": ["https://stat.columbia.edu/department-directory/ph-d-students/"],
    "cornell": ["https://stat.cornell.edu/people/phds"],
    "duke": ["https://stat.duke.edu/people/students/phd-students"],
    "florida": ["https://stat.ufl.edu/people/graduate-students/"],
    "harvard": ["https://statistics.fas.harvard.edu/graduate-students"],
    "iowa": ["https://www.stat.iastate.edu/people/graduate-students"],
    "illinois": ["https://stat.illinois.edu/directory/grad-students"],
    #"michigan": ["https://lsa.umich.edu/stats/people/phd-students.html"],
    "minnesota": ["https://cla.umn.edu/statistics/people/graduate-students"],
    "nc_state": ["https://statistics.sciences.ncsu.edu/group/grad-students/"],
    "ohio": ["https://stat.osu.edu/people?field_appointment_target_id[26]=26"],
    "penn": ["https://statistics.wharton.upenn.edu/programs/phd/students/"],
    "penn_state": [
        "https://science.psu.edu/people?person_type=48&department=17&unit=All&items_per_page=200"
    ],
    "purdue": ["https://www.stat.purdue.edu/people/graduate_students/index.html"],
    #"rice": ["https://statistics.rice.edu/people/graduate-students"],
    "rutgers": ["https://statistics.rutgers.edu/people-pages/graduate-students"],
    "stanford": ["https://statistics.stanford.edu/people/phd-students"],
    "texas_am": ["https://stat.tamu.edu/people/#graduate_students-all"],
    "ucdavis": [
        "https://statistics.ucdavis.edu/people?first=&last=&title=&unit=&field_sf_person_type_target_id%5B0%5D=156",
        "https://statistics.ucdavis.edu/people?first=&last=&title=&unit=&field_sf_person_type_target_id%5B156%5D=156&page=1"
        "https://statistics.ucdavis.edu/people?first=&last=&title=&unit=&field_sf_person_type_target_id%5B156%5D=156&page=2",
        "https://statistics.ucdavis.edu/people?first=&last=&title=&unit=&field_sf_person_type_target_id%5B156%5D=156&page=3",
        "https://statistics.ucdavis.edu/people?first=&last=&title=&unit=&field_sf_person_type_target_id%5B156%5D=156&page=4",
        "https://statistics.ucdavis.edu/people?first=&last=&title=&unit=&field_sf_person_type_target_id%5B156%5D=156&page=5",
    ],
    "uci": ["https://www.stat.uci.edu/grad-student-directory/"],
    "ucla": ["http://directory.stat.ucla.edu/active_students/ph-d-students/"],
    "uiuc": ["https://stat.illinois.edu/directory/grad-students"],
    "unc": ["https://stor.unc.edu/people/graduate-students/"],
    #"utaustin": ["https://stat.utexas.edu/people?type=Graduate%20Students"],
    "washington": ["https://stat.uw.edu/about-us/people/students/phd"],
    "wisconsin": ["https://stat.wisc.edu/ms-and-phd-graduate-student-directory/"],
    "yale": ["https://statistics.yale.edu/people/graduate-students"],
}

FACULTY_NAME_TAG = {
    "berkeley": "h3",
    "chicago": "li",
    "cmu": "a",
    "columbia": "a",
    "cornell": "span",
    "duke": "div",
    "florida": "div",
    "harvard": "h1",
    "iowa": "div",
    "illinois": "div",
    "minnesota": "a",
    "nc_state": "a",
    "ohio": "div",
    "penn": "div",
    "penn_state": "div",
    "purdue": "div",
    "rutgers": "h2",
    "stanford": "div",
    "texas_am": "li",
    "ucdavis": "span",
    "uci": "a",
    "ucla": "div",
    "uiuc": "div",
    "unc": "div",
    "washington": "span",
    "wisconsin": "a",
    "yale": "div",
}

PHD_NAME_TAG = {
    "berkeley": "h3",
    "chicago": "li",
    "cmu": "a",
    "columbia": "a",
    "cornell": "span",
    "duke": "div",
    "florida": "div",
    "harvard": "h1",
    "iowa": "div",
    "minnesota": "div",
    "nc_state": "a",
    "ohio": "div",
    "penn": "div",
    "penn_state": "div",
    "purdue": "div",
    "rutgers": "h4",
    "stanford": "div",
    "texas_am": "li",
    "ucdavis": "span",
    "uci": "div",
    "ucla": "div",
    "uiuc": "div",
    "unc": "div",
    "washington": "span",
    "wisconsin": "a",
    "yale": "div",
}

FACULTY_NAME_ROW_TAG = {
    "chicago": "h5",
    "duke": "a",
    "florida": "h3",
    "iowa": "a",
    "minnesota": "a",
    "purdue": "h2",
    "stanford": "h3",
    "texas_am": "h3",
    "ucla": ["abcfslSpanMP1", "abcfslSpanMP3"],
}

PHD_NAME_ROW_TAG = {
    "chicago": "h5",
    "duke": "h4",
    "florida": "p",
    "purdue": "h2",
    "stanford": "h3",
    "texas_am": "h3",
}

FACULTY_CLASS = {
    "berkeley": "page--title",
    "chicago": "mix faculty",
    "cmu": "name",
    "columbia": "mini-row-link",
    "cornell": "name",
    "duke": "h4",
    "florida": "entry-content",
    "harvard": "node-title",
    "illinois": "field field-user--field-dircore-photo-remote field-formatter-image field-name-field-dircore-photo field-type-image field-label-hidden has-single",
    "nc_state": "name",
    "ohio": "views-field views-field-nothing",
    "penn": "wdp_listing-name",
    "penn_state": "views-field views-field-field-name",
    "purdue": "element item cat-regular_faculty",
    "rutgers": "newstitle",
    "stanford": "hb-card__title",
    "texas_am": ["Faculty", "Adjunct Faculty"],
    "ucdavis": "field field--name-title field--type-string field--label-hidden",
    "ucla": "abcfslMT2 abcfslF12_7",
    "uiuc": "field field-user--field-dircore-display-name field-formatter-string field-name-field-dircore-display-name field-type-string field-label-hidden has-single",
    "unc": "faculty-holder-strong",
    "washington": "field-content person-name",
    "wisconsin": "faculty-name",
    "yale": "views-field-name",
}

PHD_CLASS = {
    "berkeley": "page--title",
    "chicago": "mix phd-students",
    "cmu": "name",
    "columbia": "mini-row-link",
    "cornell": "name",
    "duke": "field-content",
    "florida": "entry-content",
    "harvard": "node-title",
    "iowa": "views-field views-field-title profile-title h2",
    "minnesota": "node__content",
    "nc_state": "name",
    "ohio": "views-field views-field-nothing",
    "penn": "wdp_listing-name",
    "penn_state": "views-field views-field-field-name",
    "purdue": [
        "element item cat-A",
        "element item cat-B",
        "element item cat-C",
        "element item cat-D",
        "element item cat-E",
        "element item cat-F",
        "element item cat-G",
        "element item cat-H",
        "element item cat-I",
        "element item cat-J",
        "element item cat-K",
        "element item cat-L",
        "element item cat-M",
        "element item cat-N",
        "element item cat-O",
        "element item cat-P",
        "element item cat-Q",
        "element item cat-R",
        "element item cat-S",
        "element item cat-T",
        "element item cat-U",
        "element item cat-V",
        "element item cat-W",
        "element item cat-X",
        "element item cat-Y",
        "element item cat-Z",
    ],
    "rutgers": "newstitle",
    "stanford": "hb-card__title",
    "texas_am": "Graduate Students",
    "ucdavis": "field field--name-title field--type-string field--label-hidden",
    "uci": "name",
    "ucla": "abcfslMT2 abcfslF12_7",
    "uiuc": "field field-user--field-dircore-display-name field-formatter-string field-name-field-dircore-display-name field-type-string field-label-hidden has-single",
    "unc": "faculty-holder-strong",
    "washington": "field-content person-name",
    "wisconsin": "faculty-name",
    "yale": "views-field-name",
}

ROLE_TAG = {
    "berkeley": "div",
    "cmu": "div",
    "cornell": "span",
    "duke": "div",
    "florida": "div",
    "harvard": "div",
    "nc_state": "p",
    "ohio": "div",
    "penn_state": "div",
    "purdue": "p",
    "texas_am": "div",
    "ucla": "div",
    "unc": "div",
    "ucdavis": "ul",
    "washington": "div",
    "wisconsin": "p",
    "yale": "div",
}

ROLE_NAME_TAG = {"cmu": "h3", "texas_am": "p"}

PHD_ROLE = {
    "ohio": "views-field views-field-field-your-title",
    "penn_state": "views-field views-field-field-staff-title",
    "purdue": "p",
    "yale": "views-field-field-program",
}

FACULTY_ROLE = {
    "berkeley": "field field--name-field-job-title field--type-string field--label-hidden field__item",
    "chicago": "b",
    "cmu": "filterable",
    "duke": "views-field views-field-field-appointment-titles",
    "cornell": "field-content",
    "florida": "p",
    "nc_state": "title",
    "penn_state": "views-field views-field-field-staff-title",
    "ucla": "abcfslMTPc1 abcfslF12",
    "uiuc": [
        "field field-user--field-dircore-appt-title-remote field-formatter-string field-name-field-dircore-appt-title field-type-string field-label-hidden has-single",
        "field field-user--field-dircore-appt-title-remote field-formatter-string field-name-field-dircore-appt-title field-type-string field-label-hidden has-multiple",
    ],
    "ucdavis": "vm-teaser__position",
    "purdue": "p",
    "texas_am": "p",
    "washington": "views-field views-field-field-position",
    "yale": "views-field-field-title",
}

EXCLUDED_FACULTY = [
    "Lecturer",
    "Emeritus",
    "Emerita",
    "Researcher",
    "Visiting",
    "Special",
    "Affilated",
    "Lecturers",
    "Statistics (Courtesy)",
]

EXCLUDED_PHD = ["Biostatistics", "MAS", "MS", "M.S.", "M.A.", "M.A.S."]

FACULTY_TABLE = {
    "columbia": [
        "cn-list-row cn-list-item vcard individual fulltime-faculty senior-faculty stats-department",
        "cn-list-row-alternate cn-list-item vcard individual fulltime-faculty senior-faculty stats-department",
        "cn-list-row cn-list-item vcard individual junior-faculty-tenure-track stats-department",
        "cn-list-row-alternate cn-list-item vcard individual junior-faculty-tenure-track stats-department",
        "cn-list-row cn-list-item vcard individual junior-faculty-non-tenure-track stats-department",
        "cn-list-row-alternate cn-list-item vcard individual junior-faculty-non-tenure-track stats-department",
        "cn-list-row cn-list-item vcard individual adjunct-faculty program-directors stats-department",
        "cn-list-row cn-list-item vcard individual adjunct-faculty stats-department",
        "cn-list-row-alternate cn-list-item vcard individual adjunct-faculty stats-department",
    ],
    "harvard": ["box-1522174259-page"],
    "minnesota": ["table"],
    "penn": ["wdp_listing"],
    "stanford": ["hb-grid hb-grid--cols-3"],
    "uci": ["table"],
    "wisconsin": ["faculty-list"],
}

EXCLUDED_TAGS = [
    "<a href",
    '<span class="department">',
    "<a class=",
]

NAMES_TO_CLEAN = ["unc"]
